language: java
jdk: oraclejdk12

before_install:
  - chmod +x mvnw

script: mvn -e verify

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - 13nikrom13@gmail.com
    on_failure: always
    on_success: never